### ISSUE TITLE
Cannot Get/

### ISSUE THREAD

**Issue by HADAET** [isabolic/apex-chat-region#12] opened 2018-05-26 07:48 UTC
npm WARN apex.chat.module@1.0.0 No description
npm WARN apex.chat.module@1.0.0 No repository field.

**Comment by isabolic** [comment] 2018-05-27 18:30
HI @HADAET 

can you please attach a screenshot of directory and error that you get from CLI.

**Comment by HADAET** [comment] 2018-05-28 03:40
This screenshot of directory
![image](https://user-images.githubusercontent.com/39644584/40596169-f5192052-625a-11e8-9aec-fabb2dd6de46.png)

**Comment by isabolic** [comment] 2018-05-28 09:10
Hi @HADAET I can't see the issue you have. Your title for the issue is "Cannot Get/" and description "npm WARN ..." but from CLI screenshot everything is fine. Can you be more specific?

**Comment by isabolic** [comment] 2018-06-06 12:37
no replay from user, closing issue

**Closed as completed by isabolic** 2018-06-06 12:37 UTC
